version: "3"
services:
  selenium:
    image: knappmeier/selenium-with-tunnel
    ports:
      - 2222:2222
      - 24444:24444
      - 5900:25900
    environment:
      - SEL_BROWSER_TIMEOUT_SECS=60
      - MAX_SESSIONS=10
      - SEL_RELEASE_TIMEOUT_SECS=30
