# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn check:format
      - run: yarn check:lint --max-warnings=0

  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: docker-compose up -d
      - run: yarn install
      - run: yarn test:jest
      - run: docker-compose down

  test-docker-selenium:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: docker-compose up -d
      - run: yarn install
      - run: yarn build-storybook
      - run: yarn test:docker-selenium
        env:
          DEBUG: "addon-storyshots-selenium:*"
      - name: Upload snapshots and diffs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: docker-selenium-snapshots-node-${{ matrix.node-version }}
          path: integration-test/docker-selenium.test.ts-snapshots/**/__diff_output__/*.png
      - run: docker-compose down

  test-browserstack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build-storybook
      - run: yarn test:browserstack
        env:
          DEBUG: "addon-storyshots-selenium:*"
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      - name: Upload snapshots and diffs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: browserstack-snapshots
          path: |
            integration-test/browserstack.test.ts-snapshots/**/__diff_output__/*.png
            local.log
